# Generated by Django 6.0 on 2025-12-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminreport',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
