# Generated by Django 6.0 on 2025-12-16 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_adminreport_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminreport',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.adminprofile'),
        ),
    ]
